sudo: require
language: cpp
compiler: clang
dist: trusty

before_install:
  # From http://stackoverflow.com/a/22270645/3364162
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq


install:
  - sudo apt-get install libc++-dev

script: 
  - qmake -makefile QMAKE_CXX=$CXX QMAKE_CC=$CC QMAKE_LINK=$CXX QMAKE_CXXFLAGS+=-stdlib=libc++ travis_qmake_clang_cpp14.pro
  #- qmake -makefile QMAKE_CXX=$CXX QMAKE_CC=$CC QMAKE_LINK=clang++ QMAKE_CXXFLAGS+=-stdlib=libc++ travis_qmake_clang_cpp14.pro
  #- qmake -makefile QMAKE_CXX=$CXX QMAKE_CC=$CC QMAKE_CXXFLAGS+=-stdlib=libc++ travis_qmake_clang_cpp14.pro
  #- qmake -makefile QMAKE_CXX=$CXX QMAKE_CC=$CC QMAKE_CXXFLAGS+=-stdlib=libc++ LIBS+=-llibc++ travis_qmake_clang_cpp14.pro
  #- qmake -makefile QMAKE_CXX=$CXX QMAKE_CC=$CC QMAKE_CXXFLAGS+=-stdlib=libc++ QMAKE_LIBS+=-llibc++ travis_qmake_clang_cpp14.pro
  #- qmake -makefile QMAKE_CXX=$CXX QMAKE_CC=$CC QMAKE_CXXFLAGS+=-stdlib=libc++ QMAKE_LIBS+=-lstdlibc++ travis_qmake_clang_cpp14.pro
  - make
  - ./travis_qmake_clang_cpp14